name: Go

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Check go generate changes
        run: |
          go generate ./...
          if [[ ! -z $(git diff) ]]; then
            echo "go generate resulted in changed files. Run go generate and commit the changes."
            exit 1;
          fi
